### ISSUE TITLE
Computing mu and betas

### ISSUE THREAD

**Issue by lahmasa** [e0404/photonPencilBeamKernelCalc#1]
Hello, 

I am trying to recreate the computed mu and betas as described in [1]. My first guess would be to fit the analytical function as in the paper.
I am having trouble understanding the equations you use (lines 36, 44, 45 and 46 in ppbkc.m). Could you please explain how these were obtained?

Thank you

[1] Bortfeld, T. , Schlegel, W. and Rhein, B. (1993), Decomposition of pencil beam kernels for fast dose calculations in three‐dimensional treatment planning. Med. Phys., 20: 311-318.

**Comment by markbangert** [comment]
In line 36 that is a least squares fit for the mu to the data. If you want to know more you should contact @rainman110 and ask for a copy of his thesis. And the selection of the betas is somewhat arbitrary in my understanding. You simply need to have three components and the way we do it here should be somewhat in line with [1]. @mingersming maybe has more on that?!
