### ISSUE TITLE
primflu.dat

### ISSUE THREAD

**Issue by P705** [e0404/photonPencilBeamKernelCalc#3]
Hi
How is it obtain the primflu.dat file ?
I can't understand the effect of this file in kernel calculations.

**Comment by markbangert** [comment]
This file provides information about the primary fluence. You need to
measure this in radial direction and normalize to 1 at r= 0.

P705 <notifications@github.com> schrieb am Di., 26. Nov. 2019, 11:34:

**Comment by P705** [comment]
by using ion chamber ?

**Comment by P705** [comment]
the primary fluence was measured in one field size or different field sizes?

**Comment by markbangert** [comment]
The exact measurement method does not really matter but you should measure
an open field that covers at least the largest possible field size.
